### ISSUE TITLE
Fehlermeldungen beim kompilieren

### ISSUE THREAD

**Issue by BrunoRobert** [viisauksena/gluon-v14tov15-helper#3]
Das Skript ist eine gute Idee, wir stehen demnächst vor dem Problem der Migration von batman V14 auf v15.

Leider bekomme ich das package nicht eingebunden:  Offenbar wird in modules kein GLUON_SITE_FEED mit einem Sonderzeichen akzeptiert. Make update bringt:
`PACKAGES_V14-TO-V15-HELPER_REPO=git://github.com/viisauksena/gluon-v14tov15-helper.git: No such file or directory
make: *** [update] Fehler 1`

Wenn ich die Bindestriche lösche geht's, aber dann endet make mit dieser Fehlermeldung:
`*** No rule to make target package/gluon-v14tov15-helper/compile`

Bruno

**Comment by viisauksena** [comment]
schreib statt git:// mal https , der aktuelle Teil im Freiburger git sieht so aus .. 

```
GLUON_SITE_FEEDS='v14tov15helper ssidchanger banner treatment airtime'
PACKAGES_V14TOV15HELPER_REPO=https://github.com/viisauksena/gluon-v14tov15-helper.git
PACKAGES_V14TOV15HELPER_COMMIT=6ec8a341164be39bace245cf331d11706e5206c4
PACKAGES_V14TOV15HELPER_BRANCH=master
```

ich befürchte aber das das skript so wie hier hinterlegt noch nicht ganz funktioniert, vor allem auf den 841'ern oder andere 32mb geräten. daher könntest und solltest du das skript erstmal selber testen .. 
https://raw.githubusercontent.com/viisauksena/gluon-v14tov15-helper/master/files/lib/gluon/v14tov15-helper/v14tov15-helper
(das kannste dir leicht hier rausziehen) - bevor du das im großen Stil einbaust

**Comment by BrunoRobert** [comment]
Vielen Dank für die schnelle Antwort.
Die Fehlermeldung bleibt:
`make[1]: *** No rule to make target 'package/gluon-v14tov15-helper/compile'.  Stop.`

Bruno

**Comment by viisauksena** [comment]
du hast schon eine modules datei und darin korrekt die Dinge hinterlegt?
(wenn du mit V=s baust dann steht da einigs mehr davor an Info, wo das problem liegt)

**Comment by BrunoRobert** [comment]
Also, ich habe inzwischen herausgefunden, dass es Probleme beim Bauen der Images für D-Link DIR-615 gibt. Wenn ich diese in profiles.mk auskommentiere, geht es. Da wir vorerst doch nicht auf batman V15 umstellen, warte ich mal ab. Trotzdem Danke für dieses Tool.

**Comment by viisauksena** [comment]
das liegt aber generell daran das der 615 zu "wenig" speicher haben soll - angeblich, ich hab so ein Gerät nicht, aber kenne den Fehler
